create table if not exists public.facturas (
  id_factura bigint generated by default as identity primary key,
  folio bigint not null,
  pedido_asociado bigint not null references public.pedidos (id_pedido),
  cliente_asociado bigint not null references public.clientes (id_cliente),
  fecha_emision date not null default current_date,
  monto_neto numeric(12,2) not null default 0,
  monto_impuesto numeric(12,2) not null default 0,
  monto_total numeric(12,2) not null default 0,
  saldo_pendiente numeric(12,2) not null default 0,
  estado text not null default 'vigente'
    check (estado in ('vigente','pagada','parcialmente_pagada','anulada')),
  fecha_creacion timestamptz not null default now(),
  usuario_creacion text not null default 'Admin',
  constraint facturas_folio_unico unique (folio)
);

create index if not exists facturas_cliente_asociado_idx on public.facturas (cliente_asociado);
create index if not exists facturas_pedido_asociado_idx on public.facturas (pedido_asociado);
