-- =====================================================================
-- Incremento 3: estructura de datos para despachos, productos con
-- defectos, descuentos por cliente y vistas de informes (RF-042 a RF-055).
--
-- Escrito contra el esquema real de Supabase (proyecto Dnix Sistema)
-- al 04/10/2026. Se ejecuta completo en el SQL Editor; si algo falla,
-- no se aplica nada (transacción).
-- =====================================================================
begin;

-- ---------------------------------------------------------------------
-- 1. Descuentos por cliente (RF-001, usados en RF-047)
-- ---------------------------------------------------------------------
alter table public.clientes
  add column if not exists descuento_1 numeric(5,2) not null default 0 check (descuento_1 between 0 and 100),
  add column if not exists descuento_2 numeric(5,2) not null default 0 check (descuento_2 between 0 and 100),
  add column if not exists descuento_3 numeric(5,2) not null default 0 check (descuento_3 between 0 and 100);

-- ---------------------------------------------------------------------
-- 2. Nuevos tipos de movimiento de inventario
-- ---------------------------------------------------------------------
alter table public.movimientos_inventario
  drop constraint if exists movimientos_inventario_tipo_check;
alter table public.movimientos_inventario
  add constraint movimientos_inventario_tipo_check
  check (tipo in ('inicial', 'entrada_corte', 'salida_venta', 'merma', 'ajuste', 'baja',
                  'despacho', 'anulacion_despacho', 'defecto'));

-- ---------------------------------------------------------------------
-- 3. Despachos (RF-039, RF-042 a RF-051)
--    Cliente y vendedor se obtienen del pedido (no se duplican).
-- ---------------------------------------------------------------------
create sequence if not exists public.despachos_numero_guia_seq;

create table if not exists public.despachos (
  id_despacho      bigint generated by default as identity primary key,
  numero_guia      text not null unique
                   default ('GD-' || lpad(nextval('public.despachos_numero_guia_seq')::text, 6, '0')),
  fecha            date not null default current_date,
  id_pedido        bigint not null references public.pedidos (id_pedido),
  id_factura       bigint references public.facturas (id_factura),
  id_bodega        bigint not null references public.bodegas (id_bodega),
  via_despacho     text,
  observacion      text,
  estado           text not null default 'emitido' check (estado in ('emitido', 'anulado')),
  motivo_anulacion text,
  fecha_anulacion  timestamptz,
  usuario_creacion text not null default 'Admin',
  creado_en        timestamptz not null default now()
);

create table if not exists public.detalle_despachos (
  id_detalle_despacho  bigint generated by default as identity primary key,
  id_despacho          bigint not null references public.despachos (id_despacho) on delete cascade,
  id_detalle_pedido    bigint not null references public.detalle_pedidos (id_detalle_pedido),
  cantidad             integer not null check (cantidad > 0),
  precio_unitario      integer not null check (precio_unitario >= 0),
  descuento_porcentaje numeric(5,2) not null default 0 check (descuento_porcentaje between 0 and 100),
  constraint detalle_despachos_linea_uk unique (id_despacho, id_detalle_pedido)
);

create index if not exists despachos_id_pedido_idx on public.despachos (id_pedido);
create index if not exists despachos_id_factura_idx on public.despachos (id_factura);
create index if not exists despachos_fecha_idx on public.despachos (fecha);
create index if not exists detalle_despachos_id_detalle_pedido_idx on public.detalle_despachos (id_detalle_pedido);

-- Mismas políticas abiertas que el resto de las tablas (la app usa la
-- publishable key sin login). Se restringen en el Incremento 4 (RF-057/058).
alter table public.despachos enable row level security;
alter table public.detalle_despachos enable row level security;

drop policy if exists "Enable all access for all users" on public.despachos;
create policy "Enable all access for all users" on public.despachos
  for all using (true) with check (true);
drop policy if exists "Enable all access for all users" on public.detalle_despachos;
create policy "Enable all access for all users" on public.detalle_despachos
  for all using (true) with check (true);

-- ---------------------------------------------------------------------
-- 4. Productos con defectos (RF-053)
-- ---------------------------------------------------------------------
alter table public.inventario
  add column if not exists cantidad_defectuosa integer not null default 0
  check (cantidad_defectuosa >= 0);

-- ---------------------------------------------------------------------
-- 5. Corte asociado a un pedido, opcional (RF-054)
-- ---------------------------------------------------------------------
alter table public.cortes
  add column if not exists id_pedido bigint references public.pedidos (id_pedido);
create index if not exists cortes_id_pedido_idx on public.cortes (id_pedido);

-- ---------------------------------------------------------------------
-- 6. Funciones (se llaman desde Flask con supabase.rpc)
-- ---------------------------------------------------------------------

-- Registra un despacho completo: valida cantidades pendientes y stock,
-- descuenta inventario (queda en movimientos_inventario como 'despacho')
-- y marca el pedido como 'despachado' cuando no le queda nada pendiente.
--
-- p_lineas: [{"id_detalle_pedido": 1, "cantidad": 5, "descuento": 10}, ...]
--   "descuento" es opcional; por defecto se usan los descuentos del cliente
--   aplicados en cascada.
create or replace function public.registrar_despacho(
  p_id_pedido    bigint,
  p_id_bodega    bigint,
  p_lineas       jsonb,
  p_id_factura   bigint default null,
  p_via_despacho text   default null,
  p_observacion  text   default null,
  p_usuario      text   default 'Admin'
) returns bigint
language plpgsql
set search_path to 'public'
as $$
declare
  v_pedido      pedidos%rowtype;
  v_desc_client numeric(5,2);
  v_id_despacho bigint;
  v_guia        text;
  v_linea       jsonb;
  v_detalle     record;
  v_cantidad    integer;
  v_pendiente   integer;
  v_stock       integer;
begin
  select * into v_pedido from pedidos where id_pedido = p_id_pedido for update;
  if not found then
    raise exception 'No existe el pedido %', p_id_pedido;
  end if;
  if v_pedido.estado in ('anulado', 'despachado', 'entregado') then
    raise exception 'El pedido % está %, no se puede despachar', v_pedido.numero_pedido, v_pedido.estado;
  end if;

  if p_lineas is null or jsonb_typeof(p_lineas) <> 'array' or jsonb_array_length(p_lineas) = 0 then
    raise exception 'El despacho debe tener al menos una línea';
  end if;

  if p_id_factura is not null and not exists (
    select 1 from facturas
    where id_factura = p_id_factura and id_pedido = p_id_pedido and estado <> 'anulada'
  ) then
    raise exception 'La factura % no corresponde al pedido % o está anulada', p_id_factura, v_pedido.numero_pedido;
  end if;

  select round(100 * (1 - (1 - coalesce(descuento_1, 0) / 100)
                         * (1 - coalesce(descuento_2, 0) / 100)
                         * (1 - coalesce(descuento_3, 0) / 100)), 2)
    into v_desc_client
    from clientes where id_cliente = v_pedido.cliente_asociado;

  insert into despachos (id_pedido, id_factura, id_bodega, via_despacho, observacion, usuario_creacion)
  values (p_id_pedido, p_id_factura, p_id_bodega, p_via_despacho, p_observacion, p_usuario)
  returning id_despacho, numero_guia into v_id_despacho, v_guia;

  perform set_config('app.tipo_movimiento', 'despacho', true);
  perform set_config('app.observacion', 'Despacho ' || v_guia, true);

  for v_linea in select * from jsonb_array_elements(p_lineas) loop
    v_cantidad := (v_linea ->> 'cantidad')::integer;
    if v_cantidad is null or v_cantidad <= 0 then
      raise exception 'Cantidad inválida en la línea %', v_linea;
    end if;

    select d.id_detalle_pedido, d.id_pedido, d.cantidad, d.cantidad_anulada, d.precio_unitario,
           pv.id_producto, pv.id_talla, pv.id_color
      into v_detalle
      from detalle_pedidos d
      join producto_variantes pv on pv.id_variante = d.id_variante
     where d.id_detalle_pedido = (v_linea ->> 'id_detalle_pedido')::bigint
       for update of d;
    if not found or v_detalle.id_pedido <> p_id_pedido then
      raise exception 'La línea % no pertenece al pedido %', v_linea ->> 'id_detalle_pedido', v_pedido.numero_pedido;
    end if;

    select v_detalle.cantidad - v_detalle.cantidad_anulada - coalesce(sum(dd.cantidad), 0)
      into v_pendiente
      from detalle_despachos dd
      join despachos de on de.id_despacho = dd.id_despacho
     where dd.id_detalle_pedido = v_detalle.id_detalle_pedido and de.estado = 'emitido';
    if v_cantidad > v_pendiente then
      raise exception 'La línea % tiene % unidades pendientes y se intentan despachar %',
        v_detalle.id_detalle_pedido, v_pendiente, v_cantidad;
    end if;

    select cantidad into v_stock
      from inventario
     where id_bodega = p_id_bodega and id_producto = v_detalle.id_producto
       and id_talla = v_detalle.id_talla and id_color = v_detalle.id_color
       for update;
    if coalesce(v_stock, 0) < v_cantidad then
      raise exception 'Stock insuficiente en la bodega % para la línea % (hay %, se piden %)',
        p_id_bodega, v_detalle.id_detalle_pedido, coalesce(v_stock, 0), v_cantidad;
    end if;

    update inventario
       set cantidad = cantidad - v_cantidad, usuario_actualizacion = p_usuario
     where id_bodega = p_id_bodega and id_producto = v_detalle.id_producto
       and id_talla = v_detalle.id_talla and id_color = v_detalle.id_color;

    insert into detalle_despachos (id_despacho, id_detalle_pedido, cantidad, precio_unitario, descuento_porcentaje)
    values (v_id_despacho, v_detalle.id_detalle_pedido, v_cantidad, v_detalle.precio_unitario,
            coalesce((v_linea ->> 'descuento')::numeric, v_desc_client, 0));
  end loop;

  perform set_config('app.tipo_movimiento', '', true);
  perform set_config('app.observacion', '', true);

  if not exists (
    select 1 from detalle_pedidos d
     where d.id_pedido = p_id_pedido
       and d.cantidad - d.cantidad_anulada > coalesce((
             select sum(dd.cantidad) from detalle_despachos dd
               join despachos de on de.id_despacho = dd.id_despacho
              where dd.id_detalle_pedido = d.id_detalle_pedido and de.estado = 'emitido'), 0)
  ) then
    update pedidos set estado = 'despachado' where id_pedido = p_id_pedido;
  end if;

  return v_id_despacho;
end $$;

-- Anula un despacho y devuelve las unidades a la bodega de origen.
-- Si el pedido había quedado 'despachado', vuelve a 'confirmado'.
create or replace function public.anular_despacho(
  p_id_despacho bigint,
  p_motivo      text,
  p_usuario     text default 'Admin'
) returns void
language plpgsql
set search_path to 'public'
as $$
declare
  v_despacho despachos%rowtype;
  v_linea    record;
begin
  select * into v_despacho from despachos where id_despacho = p_id_despacho for update;
  if not found then
    raise exception 'No existe el despacho %', p_id_despacho;
  end if;
  if v_despacho.estado = 'anulado' then
    raise exception 'El despacho % ya está anulado', v_despacho.numero_guia;
  end if;
  if coalesce(trim(p_motivo), '') = '' then
    raise exception 'Debe indicar el motivo de la anulación';
  end if;

  perform set_config('app.tipo_movimiento', 'anulacion_despacho', true);
  perform set_config('app.observacion', 'Anulación despacho ' || v_despacho.numero_guia, true);

  for v_linea in
    select dd.cantidad, pv.id_producto, pv.id_talla, pv.id_color
      from detalle_despachos dd
      join detalle_pedidos d on d.id_detalle_pedido = dd.id_detalle_pedido
      join producto_variantes pv on pv.id_variante = d.id_variante
     where dd.id_despacho = p_id_despacho
  loop
    insert into inventario (id_bodega, id_producto, id_talla, id_color, cantidad, usuario_actualizacion)
    values (v_despacho.id_bodega, v_linea.id_producto, v_linea.id_talla, v_linea.id_color, v_linea.cantidad, p_usuario)
    on conflict (id_bodega, id_producto, id_talla, id_color)
    do update set cantidad = inventario.cantidad + excluded.cantidad,
                  usuario_actualizacion = excluded.usuario_actualizacion;
  end loop;

  perform set_config('app.tipo_movimiento', '', true);
  perform set_config('app.observacion', '', true);

  update despachos
     set estado = 'anulado', motivo_anulacion = p_motivo, fecha_anulacion = now()
   where id_despacho = p_id_despacho;

  update pedidos set estado = 'confirmado'
   where id_pedido = v_despacho.id_pedido and estado = 'despachado';
end $$;

-- Mueve unidades del stock disponible a defectuosas (queda registrado
-- en movimientos_inventario como 'defecto').
create or replace function public.registrar_defectuosos(
  p_id_bodega   bigint,
  p_id_producto bigint,
  p_id_talla    bigint,
  p_id_color    bigint,
  p_cantidad    integer,
  p_observacion text default null,
  p_usuario     text default 'Admin'
) returns void
language plpgsql
set search_path to 'public'
as $$
declare
  v_stock integer;
begin
  if p_cantidad is null or p_cantidad <= 0 then
    raise exception 'La cantidad debe ser mayor que cero';
  end if;

  select cantidad into v_stock from inventario
   where id_bodega = p_id_bodega and id_producto = p_id_producto
     and id_talla = p_id_talla and id_color = p_id_color
     for update;
  if coalesce(v_stock, 0) < p_cantidad then
    raise exception 'Stock insuficiente (hay %, se marcan %)', coalesce(v_stock, 0), p_cantidad;
  end if;

  perform set_config('app.tipo_movimiento', 'defecto', true);
  perform set_config('app.observacion', coalesce(p_observacion, 'Productos con defectos'), true);

  update inventario
     set cantidad = cantidad - p_cantidad,
         cantidad_defectuosa = cantidad_defectuosa + p_cantidad,
         usuario_actualizacion = p_usuario
   where id_bodega = p_id_bodega and id_producto = p_id_producto
     and id_talla = p_id_talla and id_color = p_id_color;

  perform set_config('app.tipo_movimiento', '', true);
  perform set_config('app.observacion', '', true);
end $$;

-- ---------------------------------------------------------------------
-- 7. Vistas de informes. Flask filtra por fechas, cliente, vendedor, etc.
-- ---------------------------------------------------------------------

-- Cantidad pedida, anulada, despachada y pendiente por línea de pedido.
-- Base de RF-042/043, RF-053 y RF-054.
create or replace view public.v_detalle_pedido_pendiente
with (security_invoker = true) as
select p.id_pedido,
       p.numero_pedido,
       p.fecha_pedido,
       p.fecha_entrega,
       p.estado,
       p.cliente_asociado  as id_cliente,
       c.nombre            as cliente,
       p.vendedor_asociado as id_vendedor,
       v.nombre            as vendedor,
       d.id_detalle_pedido,
       pv.id_variante,
       pv.id_producto,
       pr.descripcion      as producto,
       pv.id_color,
       co.descripcion      as color,
       pv.id_talla,
       t.talla,
       d.cantidad          as cantidad_pedida,
       d.cantidad_anulada,
       coalesce(x.despachada, 0)                                  as cantidad_despachada,
       d.cantidad - d.cantidad_anulada - coalesce(x.despachada, 0) as cantidad_pendiente
  from detalle_pedidos d
  join pedidos p             on p.id_pedido = d.id_pedido
  join producto_variantes pv on pv.id_variante = d.id_variante
  left join productos pr     on pr.id_producto = pv.id_producto
  left join colores co       on co.id_color = pv.id_color
  left join tallas t         on t.id_talla = pv.id_talla
  left join clientes c       on c.id_cliente = p.cliente_asociado
  left join vendedores v     on v.id_vendedor = p.vendedor_asociado
  left join lateral (
    select sum(dd.cantidad) as despachada
      from detalle_despachos dd
      join despachos de on de.id_despacho = dd.id_despacho
     where dd.id_detalle_pedido = d.id_detalle_pedido and de.estado = 'emitido'
  ) x on true
 where p.estado <> 'anulado';

-- RF-042/043: productos pendientes de despacho y cuánto stock hay para ellos.
-- stock_disponible es el total de todas las bodegas; si varios pedidos piden
-- la misma variante, lo comparten.
create or replace view public.v_pendientes_despacho
with (security_invoker = true) as
select dp.*,
       coalesce(s.stock, 0)                            as stock_disponible,
       least(dp.cantidad_pendiente, coalesce(s.stock, 0)) as cantidad_lista_para_despacho
  from v_detalle_pedido_pendiente dp
  left join (
    select id_producto, id_talla, id_color, sum(cantidad) as stock
      from inventario group by id_producto, id_talla, id_color
  ) s on s.id_producto = dp.id_producto and s.id_talla = dp.id_talla and s.id_color = dp.id_color
 where dp.cantidad_pendiente > 0;

-- RF-045 a RF-050: una fila por producto despachado, con pedido, cliente,
-- vendedor, factura, precio y descuento.
create or replace view public.v_despachos_detalle
with (security_invoker = true) as
select de.id_despacho,
       de.numero_guia,
       de.fecha,
       date_trunc('month', de.fecha)::date as mes,
       de.estado,
       de.id_bodega,
       b.descripcion          as bodega,
       de.via_despacho,
       p.id_pedido,
       p.numero_pedido,
       p.cliente_asociado     as id_cliente,
       c.nombre               as cliente,
       p.vendedor_asociado    as id_vendedor,
       v.nombre               as vendedor,
       de.id_factura,
       f.numero_factura,
       dd.id_detalle_despacho,
       pv.id_variante,
       pv.id_producto,
       pr.descripcion         as producto,
       co.descripcion         as color,
       t.talla,
       dd.cantidad,
       dd.precio_unitario,
       dd.descuento_porcentaje,
       dd.cantidad * dd.precio_unitario                                    as subtotal_bruto,
       round(dd.cantidad * dd.precio_unitario * dd.descuento_porcentaje / 100) as monto_descuento,
       dd.cantidad * dd.precio_unitario
         - round(dd.cantidad * dd.precio_unitario * dd.descuento_porcentaje / 100) as subtotal_neto
  from detalle_despachos dd
  join despachos de          on de.id_despacho = dd.id_despacho
  join pedidos p             on p.id_pedido = de.id_pedido
  join detalle_pedidos d     on d.id_detalle_pedido = dd.id_detalle_pedido
  join producto_variantes pv on pv.id_variante = d.id_variante
  left join productos pr     on pr.id_producto = pv.id_producto
  left join colores co       on co.id_color = pv.id_color
  left join tallas t         on t.id_talla = pv.id_talla
  left join clientes c       on c.id_cliente = p.cliente_asociado
  left join vendedores v     on v.id_vendedor = p.vendedor_asociado
  left join facturas f       on f.id_factura = de.id_factura
  left join bodegas b        on b.id_bodega = de.id_bodega;

-- RF-051: pedidos y despachos por mes.
create or replace view public.v_pedidos_despachos_mensual
with (security_invoker = true) as
with ped as (
  select date_trunc('month', p.fecha_pedido)::date as mes,
         count(distinct p.id_pedido)                as pedidos,
         coalesce(sum(d.cantidad - d.cantidad_anulada), 0) as unidades_pedidas
    from pedidos p
    left join detalle_pedidos d on d.id_pedido = p.id_pedido
   where p.estado <> 'anulado'
   group by 1
), des as (
  select date_trunc('month', de.fecha)::date as mes,
         count(distinct de.id_despacho)       as despachos,
         coalesce(sum(dd.cantidad), 0)        as unidades_despachadas
    from despachos de
    left join detalle_despachos dd on dd.id_despacho = de.id_despacho
   where de.estado = 'emitido'
   group by 1
)
select coalesce(ped.mes, des.mes)              as mes,
       coalesce(ped.pedidos, 0)                as pedidos,
       coalesce(ped.unidades_pedidas, 0)       as unidades_pedidas,
       coalesce(des.despachos, 0)              as despachos,
       coalesce(des.unidades_despachadas, 0)   as unidades_despachadas
  from ped full outer join des on des.mes = ped.mes;

-- RF-053: stock, defectuosos y unidades comprometidas en pedidos.
-- unidades_comprometidas es el total pendiente de todos los pedidos para
-- esa variante (no distingue bodega).
create or replace view public.v_inventario_analisis
with (security_invoker = true) as
select i.id_inventario,
       i.id_bodega,
       b.descripcion          as bodega,
       i.id_producto,
       pr.descripcion         as producto,
       i.id_talla,
       t.talla,
       i.id_color,
       co.descripcion         as color,
       i.cantidad             as stock_disponible,
       i.cantidad_defectuosa,
       coalesce(pp.pendiente, 0)       as unidades_comprometidas,
       coalesce(pp.pendiente, 0) > 0   as asociado_a_pedidos,
       i.fecha_actualizacion
  from inventario i
  left join bodegas b    on b.id_bodega = i.id_bodega
  left join productos pr on pr.id_producto = i.id_producto
  left join tallas t     on t.id_talla = i.id_talla
  left join colores co   on co.id_color = i.id_color
  left join (
    select id_producto, id_talla, id_color, sum(cantidad_pendiente) as pendiente
      from v_detalle_pedido_pendiente
     where cantidad_pendiente > 0
     group by id_producto, id_talla, id_color
  ) pp on pp.id_producto = i.id_producto and pp.id_talla = i.id_talla and pp.id_color = i.id_color;

-- RF-054: productos en proceso = cortes aún no ingresados a bodega.
create or replace view public.v_productos_en_proceso
with (security_invoker = true) as
select co.id_corte,
       co.fecha_corte,
       co.cortador,
       co.material_usado,
       co.cantidad,
       co.observaciones,
       co.producto_asociado as id_producto,
       pr.descripcion       as producto,
       cl.descripcion       as color,
       t.talla,
       co.id_pedido,
       p.numero_pedido,
       c.nombre             as cliente,
       (current_date - co.fecha_corte) as dias_en_proceso
  from cortes co
  left join productos pr on pr.id_producto = co.producto_asociado
  left join colores cl   on cl.id_color = pr.color
  left join tallas t     on t.id_talla = pr.talla
  left join pedidos p    on p.id_pedido = co.id_pedido
  left join clientes c   on c.id_cliente = p.cliente_asociado
 where co.estado = 'pendiente';

-- RF-052 y RF-055: producción terminada (ingresos de guías de corte a bodega).
create or replace view public.v_produccion_terminada
with (security_invoker = true) as
select m.id_movimiento,
       m.fecha,
       m.fecha::date       as dia,
       m.id_corte,
       m.id_bodega,
       b.descripcion       as bodega,
       m.id_producto,
       pr.descripcion      as producto,
       m.id_talla,
       t.talla,
       m.id_color,
       co.descripcion      as color,
       m.cantidad
  from movimientos_inventario m
  left join bodegas b    on b.id_bodega = m.id_bodega
  left join productos pr on pr.id_producto = m.id_producto
  left join tallas t     on t.id_talla = m.id_talla
  left join colores co   on co.id_color = m.id_color
 where m.tipo = 'entrada_corte';

commit;
