create table if not exists public.inventario (
  id_inventario bigint generated by default as identity primary key,
  id_bodega bigint not null,
  id_producto bigint not null,
  id_talla bigint not null,
  id_color bigint not null,
  cantidad integer not null default 0 check (cantidad >= 0),
  constraint inventario_ubicacion_producto_unica
    unique (id_bodega, id_producto, id_talla, id_color)
);

create index if not exists inventario_id_bodega_idx on public.inventario (id_bodega);
create index if not exists inventario_id_producto_idx on public.inventario (id_producto);
create index if not exists inventario_id_talla_idx on public.inventario (id_talla);
create index if not exists inventario_id_color_idx on public.inventario (id_color);
