create table if not exists public.notas_credito (
  id_nota_credito bigint generated by default as identity primary key,
  folio bigint not null,
  factura_referencia bigint not null references public.facturas (id_factura),
  cliente_asociado bigint not null references public.clientes (id_cliente),
  fecha date not null default current_date,
  monto_neto numeric(12,2) not null default 0,
  monto_impuesto numeric(12,2) not null default 0,
  monto_total numeric(12,2) not null default 0,
  motivo text not null,
  estado text not null default 'vigente'
    check (estado in ('vigente','anulada','aplicada')),
  fecha_creacion timestamptz not null default now(),
  usuario_creacion text not null default 'Admin',
  constraint notas_credito_folio_unico unique (folio)
);

create index if not exists notas_credito_factura_referencia_idx on public.notas_credito (factura_referencia);
create index if not exists notas_credito_cliente_asociado_idx on public.notas_credito (cliente_asociado);
