create table if not exists public.pagos (
  id_pago bigint generated by default as identity primary key,
  folio bigint generated by default as identity unique,
  cliente_asociado bigint not null references public.clientes (id_cliente),
  fecha_pago date not null default current_date,
  monto numeric(12,2) not null default 0,
  medio_pago text not null,
  referencia text,
  estado text not null default 'vigente'
    check (estado in ('vigente','anulada')),
  motivo_anulacion text,
  fecha_creacion timestamptz not null default now(),
  usuario_creacion text not null default 'Admin'
);

create table if not exists public.pago_facturas (
  id_pago_factura bigint generated by default as identity primary key,
  id_pago bigint not null references public.pagos (id_pago) on delete cascade,
  id_factura bigint not null references public.facturas (id_factura) on delete cascade,
  monto_aplicado numeric(12,2) not null default 0,
  fecha_creacion timestamptz not null default now(),
  unique (id_pago, id_factura)
);

create index if not exists pagos_cliente_asociado_idx on public.pagos (cliente_asociado);
create index if not exists pagos_fecha_pago_idx on public.pagos (fecha_pago);
create index if not exists pago_facturas_id_pago_idx on public.pago_facturas (id_pago);
create index if not exists pago_facturas_id_factura_idx on public.pago_facturas (id_factura);

-- Observación de negocio:
-- al aplicar o revertir un pago, la lógica debe recalcular facturas.saldo_pendiente
-- y facturas.estado ('vigente'|'parcialmente_pagada'|'pagada') dentro de la app.
